---

- hosts: all
  become: true
  tasks:

    - name: update repository index (Ubuntu)
      apt:
        update_cache: yes
      when: ansible_distribution == "Ubuntu"

    - name: install apache2 package (Ubuntu)
      apt:
        name:
          - apache2
          - libapache2-mod-php
        state: latest
      when: ansible_distribution == "Ubuntu"

    - name: add php support for apache (Ubuntu)
      apt:
        name: libapache2-mod-php
        state: latest
      when: ansible_distribution == "Ubuntu"

    - name: update repository index (RedHat)
      dnf:
        update_cache: yes
      when: ansible_distribution == "RedHat"

    - name: install apache2 package and php packages (RedHat)
      dnf:
        name:
          - httpd
          - php
        state: latest
      when: ansible_distribution == "RedHat"

