---

- hosts: all
  become: true
  tasks:

    - name: install apache2 package and modulul de php pentru Apache libapache2-mod-php
      package:
        name:
          - "{{ apache_package }}"
          - "{{ php_package }}"
        state: latest
        update_cache: yes
